server:
  name: "project-api"
  addr: ":80"
zap:
  debugFileName: "/Users/dean/GoWorks/src/handitem/ms_project/logs/debug/project-debug.log"
  infoFileName: "/Users/dean/GoWorks/src/handitem/ms_project/logs/info/project-info.log"
  warnFileName: "/Users/dean/GoWorks/src/handitem/ms_project/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"